import { z } from 'zod';

// Base Schema for creating a new user (usually via a sign-up form)
export const createUserSchema = z.object({
	// 'id' and 'emailVerified' are omitted as they are typically generated by Prisma/Database or handled separately.

	name: z.string({
		message: 'Name is required',
	})
		.min(1, 'Name cannot be empty')
		.max(255, 'Name is too long'),

	email: z.email({
		message: 'Email is required',
	})
		.max(255, 'Email is too long'),

	password: z.string({
		message: 'Password is required',
	})
		.min(8, 'Password must be at least 8 characters')
		.max(100, 'Password is too long'),
	// Note: You should hash the password before saving to the database.

	jabatan: z.string()
		.max(255, 'Jabatan (Position) is too long')
		.optional()
		.nullable(), // Allows null, matching the Prisma model's 'String?'

	isAdmin: z.boolean().default(false).optional(),
});

// TypeScript type inference for the creation data
export type CreateUserInput = z.infer<typeof createUserSchema>;

// Function to safely convert empty strings or nulls to undefined
const preprocessOptionalString = (val: any) => 
    val === '' || val === null ? undefined : val;

// Schema for updating an existing user's profile
export const updateUserSchema = createUserSchema.partial().extend({
	// Password can be null or undefined, but if provided, must be at least 8 characters
	password: z.preprocess(
        preprocessOptionalString,
        z.string()
          .min(8, 'Password must be at least 8 characters')
          .max(100, 'Password is too long')
          .optional() // 👈 Make the inner validation optional
    ).optional(),
});

// TypeScript type inference for the update data
export type UpdateUserInput = z.infer<typeof updateUserSchema>;